import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head'
import NavBar from "../../Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hisfis",
  description: "Generated by create next app",
  icons:{
    icon:[
      "./favicon.ico?1",
    ],
       
  },
  manifest:"/site.webmanifest"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <header>
        <NavBar/>
      </header>
      <main className='main-container'>
        {children}
        </main>
        </body>
     
    </html>
  );
}
