import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head'
import NavBar from "../../Components/Navbar";
import MainContainer from "../../Components/NaveBarHelp"; // Import the MainContainer component

// Define the interface for metadata
interface MyMetadata extends Metadata {
  title: string;
  description: string;
  icons?: {
    icon: string[];
  };
  manifest: string;
}

const inter = Inter({ subsets: ["latin"] });

const metadata: MyMetadata = {
  title: "Hisfis",
  description: "Generated by create next app",
  icons:{
    icon:[
      "./favicon.ico?1",
    ],
       
  },
  manifest:"/site.webmanifest"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add other meta tags and links here */}
        <link rel="manifest" href={metadata.manifest} />
        {metadata?.icons?.icon?.map((icon:string, index:number) => (
          <link key={index} rel="icon" href={icon} />
        ))}
      </Head>
      <body className={inter.className}>
        <MainContainer>{children}</MainContainer> {/* Use the MainContainer component */}
      </body>
    </html>
  );
}
